# Python3 File generated by the BNF Converter (bnfc 2.9.6).

from dataclasses import dataclass


class Exp: ...


@dataclass
class EAdd(Exp):
    exp1: Exp
    exp2: Exp


@dataclass
class ESub(Exp):
    exp1: Exp
    exp2: Exp


@dataclass
class EMul(Exp):
    exp1: Exp
    exp2: Exp


@dataclass
class EDiv(Exp):
    exp1: Exp
    exp2: Exp


@dataclass
class EInt(Exp):
    integer: int

