# Python3 File generated by the BNF Converter (bnfc 2.9.6).

from typing import assert_never
from antlr4 import CommonTokenStream
from antlr4.tree.Tree import TerminalNodeImpl

from .ast import Exp, EAdd, ESub, EMul, EDiv, EInt
from .CalcParser import CalcParser
from .CalcLexer import CalcLexer


def buildint(ctx: TerminalNodeImpl) -> int:
    return int(ctx.getText())



def buildExp(ctx: CalcParser.ExpContext) -> Exp:
    match type(ctx):
        case CalcParser.EAddContext:
            exp1 = buildExp(ctx.children[0])
            exp2 = buildExp1(ctx.children[2])
            return EAdd(exp1, exp2)
        case CalcParser.ESubContext:
            exp1 = buildExp(ctx.children[0])
            exp2 = buildExp1(ctx.children[2])
            return ESub(exp1, exp2)
        case CalcParser.Coercion_Exp_3Context:
            return buildExp1(ctx.children[0])
        case _:
            assert_never(type(ctx))  # type: ignore


def buildExp1(ctx: CalcParser.Exp1Context) -> Exp:
    match type(ctx):
        case CalcParser.EMulContext:
            exp1 = buildExp1(ctx.children[0])
            exp2 = buildExp2(ctx.children[2])
            return EMul(exp1, exp2)
        case CalcParser.EDivContext:
            exp1 = buildExp1(ctx.children[0])
            exp2 = buildExp2(ctx.children[2])
            return EDiv(exp1, exp2)
        case CalcParser.Coercion_Exp1_3Context:
            return buildExp2(ctx.children[0])
        case _:
            assert_never(type(ctx))  # type: ignore


def buildExp2(ctx: CalcParser.Exp2Context) -> Exp:
    match type(ctx):
        case CalcParser.EIntContext:
            integer = buildint(ctx.children[0])
            return EInt(integer)
        case CalcParser.Coercion_Exp2_2Context:
            return buildExp(ctx.children[1])
        case _:
            assert_never(type(ctx))  # type: ignore


def build(input_stream) -> Exp:
    lexer = CalcLexer(input_stream)
    stream = CommonTokenStream(lexer)
    parser = CalcParser(stream)

    return buildExp(parser.start_Exp().children[0])
