# Python3 File generated by the BNF Converter (bnfc 2.9.6).

from typing import assert_never

from .ast import Exp, EAdd, ESub, EMul, EDiv, EInt

INDENT_SIZE = 2


def render_tokens(tokens: list[str]) -> str:
    transformed_tokens = transform_tokens(tokens)
    grouped_tokens = group_tokens(transformed_tokens)
    return '\n'.join(
        ''.join(render_token(token) for token in add_indentation(group))
        for group in grouped_tokens
    )


def render_token(token: tuple[str, str, int]) -> str:
    token_type, value, indent_shift = token
    match token_type:
        case 'text':
            return value
        case 'newline':
            return '\n'
        case 'space':
            return ' '
        case _:
            return ''


def transform_tokens(tokens: list[str]) -> list[tuple[str, str, int]]:
    result: list[tuple[str, str, int]] = []
    inside_brackets = False
    for token in tokens:
        match token:
            case '{':
                result.append(('text', token, 0))
                result.append(('newline', '', 1))
            case '}':
                drop_trailing_newlines(result)
                result.append(('newline', '', -1))
                result.append(('text', token, 0))
                result.append(('newline', '', 0))
            case '[':
                drop_trailing_spaces(result)
                result.append(('space', '', 0))
                result.append(('text', token, 0))
                inside_brackets = True
            case ']':
                drop_trailing_spaces(result)
                result.append(('text', token, 0))
                inside_brackets = False
                result.append(('space', '', 0))
            case ';':
                drop_trailing_spaces(result)
                drop_trailing_newlines(result)
                result.append(('text', token, 0))
                result.append(('newline', '', 0))
            case 'return':
                result.append(('text', token, 0))
                result.append(('space', '', 0))
            case '(' | ')' | '<' | '>' | ',' | '.':
                drop_trailing_spaces(result)
                if token in [')', ']', '}']:
                    drop_trailing_newlines(result)
                result.append(('text', token, 0))
                if token not in ['.', '('] and not inside_brackets:
                    result.append(('space', '', 0))
            case _:
                result.append(('text', token, 0))
                if not inside_brackets:
                    result.append(('space', '', 0))
    drop_trailing_spaces(result)
    drop_trailing_newlines(result)
    return result


def group_tokens(tokens: list[tuple[str, str, int]]) -> list[tuple[int, list[tuple[str, str, int]]]]:
    groups: list[tuple[int, list[tuple[str, str, int]]]] = []
    current_group: list[tuple[str, str, int]] = []
    current_indentation = 0
    for token in tokens:
        token_type, value, indent_shift = token
        match token_type:
            case 'newline':
                current_indentation += indent_shift
                groups.append((current_indentation, current_group))
                current_group = []
            case _:
                current_group.append(token)
    if current_group:
        groups.append((current_indentation, current_group))
    return groups


def add_indentation(group_with_indent: tuple[int, list[tuple[str, str, int]]]) -> list[tuple[str, str, int]]:
    indentation_level, tokens = group_with_indent
    if indentation_level > 0:
        indent = ('text', ' ' * (INDENT_SIZE * indentation_level), 0)
        tokens.insert(0, indent)
    return tokens


def drop_trailing_spaces(tokens: list[tuple[str, str, int]]) -> None:
    while tokens and tokens[-1][0] == 'space':
        tokens.pop()


def drop_trailing_newlines(tokens: list[tuple[str, str, int]]) -> None:
    while tokens and tokens[-1][0] == 'newline':
        tokens.pop()


def print_integer(value) -> str:
    return str(value)


def print_Exp(node: Exp) -> str:
    return render_tokens(prettify_Exp(node))


def print_Exp1(node: Exp) -> str:
    return render_tokens(prettify_Exp1(node))


def print_Exp2(node: Exp) -> str:
    return render_tokens(prettify_Exp2(node))


def prettify_Exp(node: Exp) -> list[str]:
    result: list[str] = []
    match node:
        case EAdd():
            result = []
            result.extend(prettify_Exp(node.exp1))
            result.append('+')
            result.extend(prettify_Exp1(node.exp2))
            return result
        case ESub():
            result = []
            result.extend(prettify_Exp(node.exp1))
            result.append('-')
            result.extend(prettify_Exp1(node.exp2))
            return result
        case EMul():
            result = []
            result.extend(prettify_Exp1(node.exp1))
            result.append('*')
            result.extend(prettify_Exp2(node.exp2))
            return result
        case EDiv():
            result = []
            result.extend(prettify_Exp1(node.exp1))
            result.append('/')
            result.extend(prettify_Exp2(node.exp2))
            return result
        case EInt():
            result = []
            result.append(str(node.integer))
            return result
        case _:
            assert_never(type(node))  # type: ignore


def prettify_Exp1(node: Exp) -> list[str]:
    result: list[str] = []
    match node:
        case EMul():
            result = []
            result.extend(prettify_Exp1(node.exp1))
            result.append('*')
            result.extend(prettify_Exp2(node.exp2))
            return result
        case EDiv():
            result = []
            result.extend(prettify_Exp1(node.exp1))
            result.append('/')
            result.extend(prettify_Exp2(node.exp2))
            return result
        case _:
            return prettify_Exp2(node)


def prettify_Exp2(node: Exp) -> list[str]:
    result: list[str] = []
    match node:
        case EInt():
            result = []
            result.append(str(node.integer))
            return result
        case _:
            result = []
            result.append('(')
            result.extend(prettify_Exp(node))
            result.append(')')
            return result
